### PR TITLE
Create cfg.mmd

### PR DESCRIPTION
**Pull request by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll**
This shows the control-flow-graph (with some arrows omitted) for the Node. It contains enough information to reconstruct how an Rpc call is handled, how a protocol message is sent out, and how the reply works.

[preview](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcblxuICBzdWJncmFwaCBNZXNzYWdpbmdTZXJ2aWNlXG4gICAgb25SZWNlaXZlXG4gICAgc2VuZFxuICBlbmRcblxuICBzdWJncmFwaCBSZXF1ZXN0SGFuZGxlclxuICAgIGNhbGxNZXRob2RcbiAgZW5kXG5cbiAgc3ViZ3JhcGggUnBjUm91dGVyXG4gICAgZGlzcGF0Y2hcbiAgZW5kXG5cbiAgc3ViZ3JhcGggU3RvcmVTZXJ2aWNlXG4gICAgc3RvcmVTZXJ2aWNlU2V0W1wic2V0XCJdXG4gIGVuZFxuXG4gIHN1YmdyYXBoIE5vZGVDb250cm9sbGVyW1wiTm9kZUNvbnRyb2xsZXIgKFJQQylcIl1cbiAgICBycGNFeGVjdXRlW1wiZXhlY3V0ZU1ldGhvZFwiXS0tPnN0b3JlU2VydmljZVNldFxuXG4gICAgZGlzcGF0Y2gtLT5ycGNFeGVjdXRlXG4gICAgY2FsbE1ldGhvZC0tPnJwY0V4ZWN1dGVcbiAgZW5kXG5cbiAgc3ViZ3JhcGggTWlkZGxld2FyZVxuICAgIElPX1NFTkRfQU5EX1dBSVRcbiAgICBJT19TRU5EXG4gICAgT1BfU0lHTlxuICAgIFdSSVRFX0NPTU1JVE1FTlQtLT5zdG9yZVNlcnZpY2VTZXRcbiAgICBJT19TRU5EX0FORF9XQUlULS0-c2VuZFxuICAgIElPX1NFTkQtLT5zZW5kXG4gIGVuZFxuXG4gIHN1YmdyYXBoIERlZmVycmFsXG4gICAgaW9TZW5kRGVmZXJyYWxzW1wicmVzb2x2ZVwiXVxuICAgIGRlZmVycmFsQ3RvcltcImNvbnN0cnVjdG9yXCJdXG4gIGVuZFxuXG4gIHN1YmdyYXBoIFNpZ25lclxuICAgIHNpZ25EaWdlc3RbXCJzaWduaW5nS2V5LnNpZ25EaWdlc3RcIl1cbiAgZW5kXG5cbiAgc3ViZ3JhcGggTm9kZVxuXG4gICAgb25SZWNlaXZlZE1lc3NhZ2VcbiAgICBvblJlY2VpdmUtLT5vblJlY2VpdmVkTWVzc2FnZVxuXG4gICAgb25SZWNlaXZlZE1lc3NhZ2UtLT5pb1NlbmREZWZlcnJhbHNcblxuICAgIG91dGdvaW5nW1wiT3V0Z29pbmcgKEV2ZW50RW1pdHRlcilcIl1cbiAgICBwcm90b2NvbE1lc3NhZ2VFdmVudENvbnRyb2xsZXItLT58c2VuZHMgb3V0IGV2ZW50cyA8YnI-YWZ0ZXIgcHJvdG9jb2wgZmluaXNoZXN8b3V0Z29pbmdcblxuICAgIE9QX1NJR04tLT5zaWduRGlnZXN0XG5cbiAgZW5kXG5cbiAgc3ViZ3JhcGggRXZlbnRDb250cm9sbGVyW1wiTm9kZUNvbnRyb2xsZXIgKEV2ZW50KVwiXVxuXG4gICAgZXZlbnRFeGVjdXRlW1wiZXhlY3V0ZU1ldGhvZFwiXS0tPnN0b3JlU2VydmljZVNldFxuICAgIG9uUmVjZWl2ZWRNZXNzYWdlLS0-ZXZlbnRFeGVjdXRlXG5cbiAgZW5kXG5cbiAgc3ViZ3JhcGggSW5zdHJ1Y3Rpb25FeGVjdXRvclxuXG4gICAgaW5pdGlhdGVQcm90b2NvbFxuXG4gICAgcnVuUHJvdG9jb2xXaXRoTWVzc2FnZVxuICAgIHByb3RvY29sTWVzc2FnZUV2ZW50Q29udHJvbGxlci0tPnJ1blByb3RvY29sV2l0aE1lc3NhZ2VcbiAgICBycGNFeGVjdXRlLS0-aW5pdGlhdGVQcm90b2NvbFxuXG4gICAgcnVuUHJvdG9jb2xcblxuICAgIGluaXRpYXRlUHJvdG9jb2wtLT5ydW5Qcm90b2NvbFxuICAgIHJ1blByb3RvY29sV2l0aE1lc3NhZ2UtLT5ydW5Qcm90b2NvbFxuXG4gICAgaW9TZW5kRGVmZXJyYWxzLS0-fHJlc3VtZXxydW5Qcm90b2NvbFxuXG4gICAgSU9fU0VORF9BTkRfV0FJVC0tPmRlZmVycmFsQ3RvclxuXG4gICAgcnVuUHJvdG9jb2wtLT5JT19TRU5EX0FORF9XQUlUXG4gICAgcnVuUHJvdG9jb2wtLT5JT19TRU5EXG4gICAgcnVuUHJvdG9jb2wtLT5PUF9TSUdOXG4gICAgcnVuUHJvdG9jb2wtLT5XUklURV9DT01NSVRNRU5UXG5cbiAgZW5kXG5cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

### CODE REVIEW

**Comment by snario** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll refer to this: https://github.com/counterfactual/monorepo/pull/1804#issuecomment-509211814

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
I've read that already, what do you want me to do?

**Comment by snario** [comment]
Reminder to add the `Store` box and to make this into a `README.md` file with references to a Chrome Extension that can render it on github.com.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
I think the task of "making these mmd diagrams somehow viewable" can be a separate PR

**Pull request merged**
