### PR TITLE
Add GetStateDepositHolderAddress method on Node

### PR DESCRIPTION
**Pull request by snario**

### CODE REVIEW

**Comment by snario** [comment]
@cf19drofxots I'm thinking of bumping it in bulk with a couple other changes

**Comment by cf19drofxots** [comment]
I generally lean towards bumping it with every incremental change to keep consistent with the notion of the package code actually changing, but effectively speaking, I suppose I digress.

**Comment by cf19drofxots** [comment]
Note that this feature is not in any published version yet.

Waiting on @snario to make a PR to update the package version for this method to be exposed.

**Comment by cf19drofxots** [comment]
https://github.com/counterfactual/monorepo/pull/1722

**Pull request merged**
