### PR TITLE
[types] Remove AppAction type

### PR DESCRIPTION
**Pull request by snario**

### CODE REVIEW

**Comment by ebryn** [comment]
It might be useful to better document `SolidityABIEncoderV2Struct` conceptually for others

**Comment by ebryn** [comment]
Like, this is essentially `any` but for data passing to Solidity, right?

**Comment by snario** [comment]
> Like, this is essentially `any` but for data passing to Solidity, right?

Yes

**Comment by snario** [comment]
> It might be useful to better document `SolidityABIEncoderV2Struct` conceptually for others

Any suggestions as to where to put this

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
@ebryn I wrote the description which currently lives at https://github.com/counterfactual/monorepo/pull/945/files#diff-352353220a3ea3fe60b14e8e9d896d7eR8 ; the important things are that it can be serialized into JSON, and can be `abi.encode`-ed

**Comment by ebryn** [comment]
> > It might be useful to better document `SolidityABIEncoderV2Struct` conceptually for others
> 
> Any suggestions as to where to put this

I think @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll's link above covers what I had in mind

**Pull request merged**
