### PR TITLE
[playground-server] Add build script

### PR DESCRIPTION
**Pull request by cf19drofxots**
Bumps package version and adds build script.

### CODE REVIEW

**Comment by cf19drofxots** [comment]
We don't _need_ to build it, but building it prevents errors from being caught too late if `tsc` fails in the heroku deployment phase.

**Comment by joelalejandro** [comment]
I'm ok with adding this as long as it's restricted to deployment builds (we shouldn't build locally).

**Comment by snario** [comment]
Yeah like @joelalejandro said, this is only needed on Heroku, it seems to me like it should be in `heroku-postbuild`.

**Comment by cf19drofxots** [comment]
> Yeah like @joelalejandro said, this is only needed on Heroku, it seems to me like it should be in heroku-postbuild.

That's exactly the point of this PR though. The postbuild already invokes `tsc` but if it ends up failing, it'll be too late and incur another cycle to fix.

> (we shouldn't build locally).

@joelalejandro the start script invokes `ts-node` (which isn't bothered by any built files, if I understand correctly), so what's the downside of having a build script that invokes `tsc` if it doesn't effect anything else?

**Comment by cf19drofxots** [comment]
This isn't a high-enough priority item to spend time on atm, closing.

**Pull request closed without merging**
