### PR TITLE
Remove requestHandler

### PR DESCRIPTION
**Pull request by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll**

### CODE REVIEW

**Comment by snario** [comment]
@joelalejandro

**Comment by joelalejandro** [comment]
I've been seeing this PR, so far so good.

**Comment by snario** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll what should we do here?

**Comment by snario** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll

**Pull request closed without merging**
