### PR TITLE
[node] Rename roles

### PR DESCRIPTION
**Pull request by cf19drofxots**
Rename `{initiating, responding}` to `{initiator, responder}`

### CODE REVIEW

**Comment by cf19drofxots** [comment]
> Should be initiating instead of initiator for consistency

For consistency yes, though `initiating` by itself was flawed to start with (it was only fine when paired with `publicIdentifer`)

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
how come initiating is flawed if not paired with `publicIdentifier`?

**Comment by cf19drofxots** [comment]
I'll rephrase: `initiator` is the entity doing the action. `initiating` by itself is not an entity unless paired with one, such as a public identifier (who'd be _initiating_ the action, or who'd be the _initiator_)

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
oh ok, can you rename `initiating` -> `initiator` across the codebase then

**Pull request merged**
