### PR TITLE
[node] selectively add 0x prefix

### LINKED ISSUE #1461: Running tests twice fails with `0x0x` in bytecode
Running the following from a fresh clone errors out

```
yarn && yarn build && yarn test && cd packages/node && yarn test
```

with the following

```
invalid hexidecimal string (arg="value", value="0x0x608060405234801561001057600080fd5b506040516020806101a88339810180604052602081101561003057600080fd5b8101908080519060200190929190505050600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff1614156100c7576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260248152602001806101846024913960400191505060405180910390fd5b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050606e806101166000396000f3fe608060405273ffffffffffffffffffffffffffffffffffffffff600054163660008037600080366000845af43d6000803e6000811415603d573d6000fd5b3d6000f3fea165627a7a72305820694407262d1bf8a12b96a9ab0006c182bd726d829087da293c23bcb1e4bd03930029496e76616c6964206d617374657220636f707920616464726573732070726f7669646564", version=4.0.27)
```

### PR DESCRIPTION
**Pull request by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll**
fixes #1461, #669

### CODE REVIEW

**Comment by snario** [comment]
Feels like a patch, not a fix?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
what's the fix?

**Comment by snario** [comment]
On the first-time around of running `yarn test` we compile the contracts for the first time time with `ethereum-waffle` (in the `contracts` package) and then a second time with `truffle` (in the `node` package). The second time around, when the tests run for the Node, it runs `truffle migrate` and tries to _recompile_ the contracts and there is some discontinuity with how `ethereum-waffle` and `truffle` handle compilation that leads to this weird result.

I think the root cause is this compilation discontinuity.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
So what if we use two methods to recompile? AFAICT it's not specified anywhere whether the `bytecode` field should start with `0x`, so the current code on master is relying on implementation details.

**Comment by snario** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll I think a temporary fix would be to delete the compiled contracts on `yarn test`. The specification is based on what the Truffle output is (`ethereum-waffle` is set to use "legacyOutput" which is _supposed to be_ the Truffle output; maybe double check that flag is working).

https://github.com/counterfactual/monorepo/blob/0c78d92716f975d5d183aed7ff4bc590be63d504/packages/contracts/waffle.js#L7

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
> The specification is based on what the Truffle output is

again, this looks like implementation behaviour to me, since truffle doesn't seem (to me) to make a guarantee about what the bytecode field should look like

**Comment by snario** [comment]
Yes @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll, correct, but that is not the issue here. The issue is that running it twice changes the behaviour, right?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
Incorrect, the issue is what is stated in the title of https://github.com/counterfactual/monorepo/issues/1461

**Comment by snario** [comment]
Sorry that is what I mean. 

I still recommend deleting the build artifacts when you start the tests.

**Comment by cf19drofxots** [comment]
This was fixed in https://github.com/counterfactual/monorepo/pull/1524

**Pull request closed without merging**
