### PR TITLE
[dapp-high-roller] Add initialState to proposeInstall in app-wager

### PR DESCRIPTION
**Pull request by Alonski**
### Description

This adds initialState to proposeVirtualInstall in `app-wager` in `dapp-high-roller`

In addition this also cleans up a bit the usage of a `const` instead of `ethers.HashZero`

This also adds a `game-types.ts` and removes an `enum.ts` file and uses the definitions where necessary.

- [ ] Deploy preview is functional

### CODE REVIEW

**Comment by cf19drofxots** [comment]
Now that #536 is merged, the playground browser console shows "A proposed AppInstance cannot have an empty initial state" as an error when a game of High Roller is about to be played.

After _this_ PR is merged, this error should be resolved.

**Comment by cf19drofxots** [comment]
@ebryn CI was failing on this branch though

**Comment by ebryn** [comment]
oh dang, it looked green

**Comment by cf19drofxots** [comment]
apparently the checks were stale, seems fine on master

**Comment by Alonski** [comment]
It failed because of the DB issue with firebase. I guess this was fixed?

**Pull request merged**
