### PR TITLE
[cf.js] Remove all usage of cf.js/legacy

### PR DESCRIPTION
**Pull request by snario**
There are only usages left:

1. [This test file](https://github.com/counterfactual/monorepo/blob/liam/a-new-era-has-begun/packages/cf.js/test/legacy/app-instance.spec.ts#L3) testing a `generateAbiEncodings` function 

2. The `Node` has a class called `Channel` which uses `legacy.utils.Nonce` and `legacy.utils.FreeBalance` as members but does not actually use any of the methods. Also, this class is going to be removed in a PR coming in the next few days.

### CODE REVIEW

**Comment by mvanderh** [comment]
@snario Is `generateAbiEncodings` actually _used_ anywhere besides the test?

**Comment by snario** [comment]
> @snario Is `generateAbiEncodings` actually _used_ anywhere besides the test?

nope

**Comment by mvanderh** [comment]
Just remove it then IMO.

**Comment by mvanderh** [comment]
Also lol @ that branch name

**Pull request merged**
