### PR TITLE
[dapp-high-roller] Create initial boilerplate High Roller dApp

### PR DESCRIPTION
**Pull request by Alonski**
### Description

Initialized Stencil app.
One thing that I found weird is that I had to have a component other than the `app-home` one for the contents of `app-home` to render.
Couldn't figure out why.

I noticed this issue with the `Playground` package as well.

### CODE REVIEW

**Comment by joelalejandro** [comment]
@Alonski The `app-root` component is the top-level element in the Stencil app hierarchy, AFAIK. I believe it has to do with the fact that this component includes `stencil-router` and the primary layout for the app.

**Comment by Alonski** [comment]
@joelalejandro Yea I understand. Right now if you run the app it will render the content inside of `app-home`. However, if you remove the `app-profile` folder and then rebuild the app all of a sudden the contents of `app-home` won't render. 

Maybe it was only happening to me?

**Comment by Alonski** [comment]
@joelalejandro Actually while running the Playground I also didn't see the home page content.

**Comment by Alonski** [comment]
@joelalejandro Found an issue for what I was describing:
https://github.com/ionic-team/stencil-router/issues/62

**Pull request merged**
