### PR TITLE
[node] IStoreService: rename key to path

### PR DESCRIPTION
**Pull request by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll**
This brings the interface in line with Firebase terminology and with how we actually treat variables with this name

### CODE REVIEW

**Comment by cf19drofxots** [comment]
Seems like this broke master but the fix should be easy?

```
remote:        src/node.ts(236,7): error TS2345: Argument of type 'import("/tmp/build_26031d705add4dfcfa39b6758d16c2bd/node_modules/@counterfactual/types/dist/src/node").Node.IStoreService' is not assignable to parameter of type 'import("/tmp/build_26031d705add4dfcfa39b6758d16c2bd/node_modules/@counterfactual/node/node_modules/@counterfactual/types/dist/src/node").Node.IStoreService'.        
remote:          Types of property 'set' are incompatible.        
remote:            Type '(pairs: { path: string; value: any; }[], allowDelete?: Boolean | undefined) => Promise<void>' is not assignable to type '(pairs: { key: string; value: any; }[], allowDelete?: Boolean | undefined) => Promise<void>'.        
remote:              Types of parameters 'pairs' and 'pairs' are incompatible.        
remote:                Type '{ key: string; value: any; }[]' is not assignable to type '{ path: string; value: any; }[]'.        
remote:                  Property 'path' is missing in type '{ key: string; value: any; }' but required in type '{ path: string; value: any; }'
```

circleci.com/gh/counterfactual/monorepo/41332

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
I think it's from the old version of types

**Comment by cf19drofxots** [comment]
But it also broke on master after the types PR was merged

https://www.circleci.com/gh/counterfactual/monorepo/41326

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
That job runs after publish to npm

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
wait, I am wrong...

**Comment by cf19drofxots** [comment]
This is now causing tests to fail on other branches not relevant to this change

https://circleci.com/gh/counterfactual/monorepo/41357

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
that circleci task shouldn't be producing a `packages/simple-hub-server/node_modules/@counterfactual/node/node_modules/@counterfactual/types` folder

**Comment by cf19drofxots** [comment]
I know, found that to be odd

**Pull request merged**
