### PR TITLE
[playground] Adds "Log out" feature

### PR DESCRIPTION
**Pull request by joelalejandro**
deepin-screen-recorder_vivaldi-stable_20190305132923

### CODE REVIEW

**Comment by snario** [comment]
Can we hide the button inside the account page vs keeping it front and center like that?

**Comment by joelalejandro** [comment]
@snario Seems a bit uncomfortable to use inside the Account page. But I guess we can do that.

**Comment by snario** [comment]
I just think it shouldn't be "always present"

**Comment by ebryn** [comment]
We can fix in subsequent PRs

**Pull request merged**
