### PR TITLE
[machine] upgrade jest

### PR DESCRIPTION
**Pull request by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll**
Needed for `extraGlobals`

### CODE REVIEW

**Comment by snario** [comment]
There's some weird stuff as mentioned #841

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
I think this is a weirder issue than that - upgrading jest on **machine** causes a require to fail in **node**. But node was already using jest 24.

**Comment by snario** [comment]
Let's do this: #1145

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
We will probably still run into the same problem, is my guess

**Comment by snario** [comment]
Check my branch #1138, too.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
Woot

**Pull request closed without merging**
