### PR TITLE
Update prototypal/jsonrpc-server

### PR DESCRIPTION
**Pull request by snario**

### CODE REVIEW

**Comment by joelalejandro** [comment]
Not really. We could publish it.

**Comment by joelalejandro** [comment]
@snario There's something wrong with the Node not finding the `rpc-server` package? I'll try publishing, but this feels weird.

**Comment by joelalejandro** [comment]
@snario Can you change `package.json` to point to this reference?

```
"rpc-server": "^0.0.1",
```

**Comment by cf19drofxots** [comment]
Are we sure about wanting `^`?

**Comment by joelalejandro** [comment]
@cf19drofxots If you feel better freezing the dependency, I'm OK with it. The `rpc-server` package is pretty much done for now.

**Pull request merged**
