### PR TITLE
[apps] Simple swap app

### PR DESCRIPTION
**Pull request by rhlsthrm**
# Description
Exchange functionality in app.

### Related issues

- [ ] Deploy preview is functional

### CODE REVIEW

**Comment by cf19drofxots** [comment]
Thanks for this - we'll probably change the base branch for this but it shouldn't effect the actual PR itself.

**Comment by rhlsthrm** [comment]
Cool, just wanted to get this into the erc20 branch before it got merged and released.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
We should do the ERC20 PR and this one in separate PRs

**Comment by cf19drofxots** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll yeah that's why I mentioned changing the base branch

**Comment by rhlsthrm** [comment]
OK, I changed the base branch to be master instead of ERC20. We can merge this after that branch is merged, please ping me when it's ready.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
You can leave the base branch as before since #1792 is a dependency of this (and also so that rebases are possible), just don't merge it into #1792

**Comment by rhlsthrm** [comment]
Changed it back to `erc20_deposit`

**Comment by ArjunBhuptani** [comment]
Updated based on a conversation with @snario today. Should be good to go!

**Comment by cf19drofxots** [comment]
Closing in favor of merging: https://github.com/counterfactual/monorepo/pull/1836

**Pull request closed without merging**
