### PR TITLE
[WIP] [node] Event emission symmetry

### PR DESCRIPTION
**Pull request by rhlsthrm**
Attempted to remove the event emission updates from this PR #1736. Unsure if this is all that needs to be done to make the events emit symmetrically. Need some assistance from @snario to continue.

### CODE REVIEW

**Comment by snario** [comment]
@joelalejandro how should we approach using `router.emit` and `outgoing.emit`?

**Comment by rhlsthrm** [comment]
@joelalejandro any update on this? Need some guidance on how to make the event emission symmetric.

**Comment by joelalejandro** [comment]
@rhlsthrm - sorry for the delayed response. In order to emit events through the new API, you should be using: 

```ts
router.emit(eventName, data, "outgoing");
```

**Comment by rhlsthrm** [comment]
@joelalejandro thanks for the info, I will do that.

In that case, it's unclear what in the PR (#1736) this code was pulled out of actually addresses the issue we are trying to resolve (emitting events symmetrically on both nodes). The only things I saw in that PR that had anything to do with events was what I put in this PR.

**Comment by cf19drofxots** [comment]
What's the status of this PR?

**Comment by rhlsthrm** [comment]
I don't think this is relevant anymore, will close for now.

**Pull request closed without merging**
